name: core-linux
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: configure OS
        run: |
          # os level stuff
          echo `pwd`
          echo `ls`
          set -x
          export DEBIAN_FRONTEND="noninteractive"
          export TZ="America/Los_Angeles"
          sudo apt-get update -qq
          sudo apt-get install -qq -y git-core gcc g++ gfortran cmake subversion automake m4 libgtest-dev libmkl-dev libmkl-gf-ilp64 libopenblas64-openmp-dev

      - name: install BLAS++
        run: |
          cd ..
          echo `pwd`
          echo `ls`
          git clone https://bitbucket.org/icl/blaspp.git
          mkdir blaspp-build
          cd blaspp-build
          cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../blaspp-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              -Dbuild_tests=OFF \
              -Dblas_int=int64 \
              ../blaspp
          make -j2 install

      - name: install LAPACK++
        run: |
          cd ..
          git clone https://bitbucket.org/icl/lapackpp.git
          mkdir lapackpp-build
          cd lapackpp-build
          cmake -DCMAKE_BUILD_TYPE=Debug \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../lapackpp-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              -Dbuild_tests=OFF \
              `pwd`/../lapackpp
          make -j2 install

      - name: install Random123  
        run: |
          cd ..
          pwd
          ls
          git clone https://github.com/DEShawResearch/Random123.git
          cd Random123/
          make prefix=`pwd`/../Random123-install install-include

      - name: build HQRRP
        run: |
          cd ..
          mkdir HQRRP-build
          cd HQRRP-build
          cmake -DCMAKE_BUILD_TYPE=Debug \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -Dlapackpp_DIR=`pwd`/../lapackpp-install/lib/lapackpp \
              -DRandom123_DIR=`pwd`/../Random123-install/include \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../HQRRP-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              `pwd`/../hqrrp
          make
          ./simple_test
          ctest
